# Generated by Django 4.2.2 on 2023-07-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0002_alter_employee_employee_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="image",
            field=models.ImageField(default=1, upload_to="employee_images/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="low_image",
            field=models.ImageField(blank=True, upload_to="employee_images/"),
        ),
    ]
